config/routes.rb
Mogu::Application.routes.draw do
  resources :novel_links

  resources :novel_pages

  root :to => "top#index"

  resources :links

  resources :pages

  resources :novels

  resources :users

end

app/models/novel.rb
# == Schema Information
#
# Table name: novels
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :string(255)
#  author     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Novel < ActiveRecord::Base
end

app/models/novel_link.rb
# == Schema Information
#
# Table name: novel_links
#
#  id         :integer          not null, primary key
#  page_id    :integer
#  to_page_id :integer
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class NovelLink < ActiveRecord::Base
  belongs_to :page
end

app/models/novel_page.rb
# == Schema Information
#
# Table name: novel_pages
#
#  id         :integer          not null, primary key
#  novel_id   :integer
#  title      :string(255)
#  body       :text
#  status     :integer
#  created_at :datetime
#  updated_at :datetime
#

class NovelPage < ActiveRecord::Base
  belongs_to :novel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/novel_links_controller.rb
class NovelLinksController < ApplicationController
  before_action :set_novel_link, only: [:show, :edit, :update, :destroy]

  # GET /novel_links
  # GET /novel_links.json
  def index
    @novel_links = NovelLink.all
  end

  # GET /novel_links/1
  # GET /novel_links/1.json
  def show
  end

  # GET /novel_links/new
  def new
    @novel_link = NovelLink.new
  end

  # GET /novel_links/1/edit
  def edit
  end

  # POST /novel_links
  # POST /novel_links.json
  def create
    @novel_link = NovelLink.new(novel_link_params)

    respond_to do |format|
      if @novel_link.save
        format.html { redirect_to @novel_link, notice: 'Novel link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @novel_link }
      else
        format.html { render action: 'new' }
        format.json { render json: @novel_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novel_links/1
  # PATCH/PUT /novel_links/1.json
  def update
    respond_to do |format|
      if @novel_link.update(novel_link_params)
        format.html { redirect_to @novel_link, notice: 'Novel link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @novel_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novel_links/1
  # DELETE /novel_links/1.json
  def destroy
    @novel_link.destroy
    respond_to do |format|
      format.html { redirect_to novel_links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novel_link
      @novel_link = NovelLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def novel_link_params
      params.require(:novel_link).permit(:page_id, :to_page_id, :name)
    end
end

app/controllers/novel_pages_controller.rb
class NovelPagesController < ApplicationController
  before_action :set_novel_page, only: [:show, :edit, :update, :destroy]

  # GET /novel_pages
  # GET /novel_pages.json
  def index
    @novel_pages = NovelPage.all
  end

  # GET /novel_pages/1
  # GET /novel_pages/1.json
  def show
  end

  # GET /novel_pages/new
  def new
    @novel_page = NovelPage.new
  end

  # GET /novel_pages/1/edit
  def edit
  end

  # POST /novel_pages
  # POST /novel_pages.json
  def create
    @novel_page = NovelPage.new(novel_page_params)

    respond_to do |format|
      if @novel_page.save
        format.html { redirect_to @novel_page, notice: 'Novel page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @novel_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @novel_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novel_pages/1
  # PATCH/PUT /novel_pages/1.json
  def update
    respond_to do |format|
      if @novel_page.update(novel_page_params)
        format.html { redirect_to @novel_page, notice: 'Novel page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @novel_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novel_pages/1
  # DELETE /novel_pages/1.json
  def destroy
    @novel_page.destroy
    respond_to do |format|
      format.html { redirect_to novel_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novel_page
      @novel_page = NovelPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def novel_page_params
      params.require(:novel_page).permit(:novel_id, :title, :body, :status)
    end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :set_novel, only: [:show, :edit, :update, :destroy]

  # GET /novels
  # GET /novels.json
  def index
    @novels = Novel.all
  end

  # GET /novels/1
  # GET /novels/1.json
  def show
  end

  # GET /novels/new
  def new
    @novel = Novel.new
  end

  # GET /novels/1/edit
  def edit
  end

  # POST /novels
  # POST /novels.json
  def create
    @novel = Novel.new(novel_params)

    respond_to do |format|
      if @novel.save
        format.html { redirect_to @novel, notice: 'Novel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @novel }
      else
        format.html { render action: 'new' }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novels/1
  # PATCH/PUT /novels/1.json
  def update
    respond_to do |format|
      if @novel.update(novel_params)
        format.html { redirect_to @novel, notice: 'Novel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novels/1
  # DELETE /novels/1.json
  def destroy
    @novel.destroy
    respond_to do |format|
      format.html { redirect_to novels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novel
      @novel = Novel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def novel_params
      params.require(:novel).permit(:title, :content, :author)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @novels  = Novel.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/novel_links_helper.rb
module NovelLinksHelper
end

app/helpers/novel_pages_helper.rb
module NovelPagesHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mogu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/novel_links/_form.html.erb
<%= form_for(@novel_link) do |f| %>
  <% if @novel_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@novel_link.errors.count, "error") %> prohibited this novel_link from being saved:</h2>

      <ul>
      <% @novel_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page %><br />
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :to_page_id %><br />
    <%= f.number_field :to_page_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/novel_links/edit.html.erb
<h1>Editing novel_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @novel_link %> |
<%= link_to 'Back', novel_links_path %>

app/views/novel_links/index.html.erb
<h1>Listing novel_links</h1>

<table>
  <thead>
    <tr>
      <th>Page</th>
      <th>To page</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @novel_links.each do |novel_link| %>
    <tr>
      <td><%= novel_link.page %></td>
      <td><%= novel_link.to_page_id %></td>
      <td><%= novel_link.name %></td>
      <td><%= link_to 'Show', novel_link %></td>
      <td><%= link_to 'Edit', edit_novel_link_path(novel_link) %></td>
      <td><%= link_to 'Destroy', novel_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Novel link', new_novel_link_path %>

app/views/novel_links/new.html.erb
<h1>New novel_link</h1>

<%= render 'form' %>

<%= link_to 'Back', novel_links_path %>

app/views/novel_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page:</strong>
  <%= @novel_link.page %>
</p>

<p>
  <strong>To page:</strong>
  <%= @novel_link.to_page_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @novel_link.name %>
</p>


<%= link_to 'Edit', edit_novel_link_path(@novel_link) %> |
<%= link_to 'Back', novel_links_path %>

app/views/novel_pages/_form.html.erb
<%= form_for(@novel_page) do |f| %>
  <% if @novel_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@novel_page.errors.count, "error") %> prohibited this novel_page from being saved:</h2>

      <ul>
      <% @novel_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :novel %><br />
    <%= f.text_field :novel %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/novel_pages/edit.html.erb
<h1>Editing novel_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @novel_page %> |
<%= link_to 'Back', novel_pages_path %>

app/views/novel_pages/index.html.erb
<h1>Listing novel_pages</h1>

<table>
  <thead>
    <tr>
      <th>Novel</th>
      <th>Title</th>
      <th>Body</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @novel_pages.each do |novel_page| %>
    <tr>
      <td><%= novel_page.novel %></td>
      <td><%= novel_page.title %></td>
      <td><%= novel_page.body %></td>
      <td><%= novel_page.status %></td>
      <td><%= link_to 'Show', novel_page %></td>
      <td><%= link_to 'Edit', edit_novel_page_path(novel_page) %></td>
      <td><%= link_to 'Destroy', novel_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Novel page', new_novel_page_path %>

app/views/novel_pages/new.html.erb
<h1>New novel_page</h1>

<%= render 'form' %>

<%= link_to 'Back', novel_pages_path %>

app/views/novel_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Novel:</strong>
  <%= @novel_page.novel %>
</p>

<p>
  <strong>Title:</strong>
  <%= @novel_page.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @novel_page.body %>
</p>

<p>
  <strong>Status:</strong>
  <%= @novel_page.status %>
</p>


<%= link_to 'Edit', edit_novel_page_path(@novel_page) %> |
<%= link_to 'Back', novel_pages_path %>

app/views/novels/_form.html.erb
<%= form_for(@novel) do |f| %>
  <% if @novel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@novel.errors.count, "error") %> prohibited this novel from being saved:</h2>

      <ul>
      <% @novel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/novels/edit.html.erb
<h1>Editing novel</h1>

<%= render 'form' %>

<%= link_to 'Show', @novel %> |
<%= link_to 'Back', novels_path %>

app/views/novels/index.html.erb
<h1>Listing novels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @novels.each do |novel| %>
    <tr>
      <td><%= novel.title %></td>
      <td><%= novel.content %></td>
      <td><%= novel.author %></td>
      <td><%= link_to 'Show', novel %></td>
      <td><%= link_to 'Edit', edit_novel_path(novel) %></td>
      <td><%= link_to 'Destroy', novel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Novel', new_novel_path %>

app/views/novels/new.html.erb
<h1>New novel</h1>

<%= render 'form' %>

<%= link_to 'Back', novels_path %>

app/views/novels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @novel.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @novel.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @novel.author %>
</p>


<%= link_to 'Edit', edit_novel_path(@novel) %> |
<%= link_to 'Back', novels_path %>

app/views/top/index.html.erb
<h1>rails4課題用サイトのトップ</h1>
仕様：ノベルゲーム作成＆プレイサイト<br>
なんかページ作ってレッツプレイ的なそんな雰囲気<br>
<h3>めにゅー</h3>
<%= link_to "ノベル管理", novels_url %>
<%= link_to "ページ管理", novel_pages_url %>
<%= link_to "リンク管理", novel_links_url %><br>

<h3>ノベル一覧</h3>
<% @novels.each do |n| %>
  <%= link_to n.title, novel_url(n) %> by <%= n.author %><br>
  [<%= n.content %>]<br><br>
<% end %>